/* 
 * Customer API
 *
 * This is a customer API. It produces ?
 *
 * OpenAPI spec version: 1.0.0
 * Contact: chwelt88@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Customer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CustomerTests
    {
        // TODO uncomment below to declare an instance variable for Customer
        //private Customer instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Customer
            //instance = new Customer();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Customer
        /// </summary>
        [Test]
        public void CustomerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Customer
            //Assert.IsInstanceOfType<Customer> (instance, "variable 'instance' is a Customer");
        }


        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Test]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }
        /// <summary>
        /// Test the property 'AccountValue'
        /// </summary>
        [Test]
        public void AccountValueTest()
        {
            // TODO unit test for the property 'AccountValue'
        }
        /// <summary>
        /// Test the property 'CustomerName'
        /// </summary>
        [Test]
        public void CustomerNameTest()
        {
            // TODO unit test for the property 'CustomerName'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Contacts'
        /// </summary>
        [Test]
        public void ContactsTest()
        {
            // TODO unit test for the property 'Contacts'
        }

    }

}
